name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update || true
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev || true
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer init
          echo "[app]" >> buildozer.spec
          echo "title = MiApp" >> buildozer.spec
          echo "package.name = miapp" >> buildozer.spec
          echo "package.domain = org.miapp" >> buildozer.spec
          echo "requirements = python3, kivy==2.0.0, kivymd==0.104.2" >> buildozer.spec
          echo "android.permissions = INTERNET" >> buildozer.spec
          buildozer -v android debug > buildozer.log 2>&1
          cat buildozer.log

      - name: Upload APK
        if: success()  # Solo sube si el paso anterior tuvo éxito
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
