name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk \
          autoconf libtool pkg-config zlib1g-dev libncurses5-dev \
          libncursesw5-dev cmake libffi-dev libssl-dev

      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install buildozer==1.5.0 cython

      - name: Prepare environment
        run: |
          mkdir -p ~/.buildozer/android/platform
          echo "[buildozer]\nlog_level = 2" > ~/.buildozerrc

      - name: Build APK
        run: |
          buildozer init
          buildozer -v android debug 2>&1 | tee buildozer.log
          cat buildozer.log

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
