name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build with Ubuntu and manual setup
        run: |
          # Usar Ubuntu base y hacer TODO manualmente
          docker run --rm -v $(pwd):/app ubuntu:22.04 /bin/bash -c "
          # Actualizar e instalar dependencias
          apt-get update && apt-get install -y \
              git zip unzip python3-pip autoconf libtool pkg-config \
              zlib1g-dev libncurses5-dev libncursesw5-dev libffi-dev \
              libssl-dev cython3 openjdk-17-jdk curl wget unzip
    
          # Instalar Buildozer
          pip install buildozer
    
          # Configurar Buildozer para usar SDK existente (si lo tienes)
          cd /app && buildozer -v android debug
          "

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-failure-logs
          path: |
            .buildozer
            **/*.log
