name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build with official Kivy image
        run: |
          # Usar la imagen OFICIAL de Kivy (garantizada que existe)
          docker run --rm -v $(pwd):/app \
            -e FIREBASE_PRIVATE_KEY_ID="$FIREBASE_PRIVATE_KEY_ID" \
            -e FIREBASE_PRIVATE_KEY="$FIREBASE_PRIVATE_KEY" \
            -e FIREBASE_CLIENT_EMAIL="$FIREBASE_CLIENT_EMAIL" \
            -e FIREBASE_CLIENT_ID="$FIREBASE_CLIENT_ID" \
            kivy/buildozer:latest buildozer -v android debug
        env:
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-failure-logs
          path: |
            .buildozer
            **/*.log
